#!/usr/bin/python

from __future__ import print_function
from Adafruit_Thermal import *
from random import choice

printer   = Adafruit_Thermal("/dev/serial0", 19200, timeout=5)

jokes = [['Where does a vampire water-ski', 'On Lake Erie.'],
 ['Where do baby ghosts go during the day', 'To the day-scare center.'],
 ['What do ghosts serve for dessert', 'Ice scream.'],
 ['Which story do the little witches like to hear at bedtime',
  'Ghoul Deluxe and the Three Scares.'],
 ['What are the days of the vampire week',
  'Moon-day, Tooth-day, Veins-day, Thirst-day, and Fright-day.'],
 ['What did the skeleton say to the vampire', 'You suck.'],
 ['Why did the mummy call the doctor', 'Because he was coffin.'],
 ["What do you call a witch's garage", 'The broom closet.'],
 ['Who was the most famous French skeleton', 'Napoleon Bone-apart.'],
 ['Why did the dyslexic vampire starve to death',
  "He couldn't find any doolb."],
 ['Why do mummies make excellent spies',
  "They're good at keeping things under wraps."],
 ['What type of pet dog do vampires like the best', 'Bloodhounds.'],
 ["Why can't a skeleton have fingers more than 11 inches long",
  'Because 12 inches is a foot.'],
 ['What is Transylvania', 'Vampire terror-tory.'],
 ['Why are most monsters covered in wrinkles',
  'Have you ever tried to iron a monster?'],
 ["What do you call someone who puts poison in a person's corn flakes",
  'A cereal killer.'],
 ['What kinds of mistakes do ghosts make', 'Boo boos.'],
 ['What do you call a drunken ghost', 'A methylated spirit.'],
 ["What is a ghost's favorite type of music", 'Haunting melodies.'],
 ["What is a Mummy's favorite type of music", 'Wrap!'],
 ['Why did the monster eat a light bulb',
  'Because he was in need of a light snack.'],
 ['How do you make a witch scratch', 'Take away the "w."'],
 ['What do you get when you cross a vampire and a werewolf',
  'A fur coat that fangs around your neck.'],
 ['What does a vampire fear most', 'Tooth decay.'],
 ["Why don't skeletons ever go out on the town",
  "Because they don't have any body to go out with."],
 ['How do monsters know their future', 'They read their horror-scopes.'],
 ['What do you call a witch who lives at the beach', 'A sand-witch.'],
 ['Where does a vampire have lunch', 'At the casketeria.'],
 ['What do you call a friendly dead pharaoh', 'A chummy mummy.'],
 ['Where do ghosts live', 'In a far distant terror-tory.'],
 ['Why was the baby vampire scared to go to the bathroom',
  'Because he was afraid of the light.'],
 ['Did you hear about the unsuccessful vampire hunter',
  'He tried to kill a vampire by driving a pork chop through its heart because steaks were too expensive.'],
 ['What did the ghost buy for his haunted house', 'Home moaners insurance.'],
 ["What is a vampire's favorite mode of transportation", 'A blood vessel.'],
 ['Do monsters eat popcorn with their fingers',
  'No, they eat the fingers separately.'],
 ['What do you call a haunted chicken', 'A poultry-geist.'],
 ['Why are vampires stupid', 'Because they are all suckers.'],
 ['What kind of monster is safe to put in the washing machine',
  'A wash-and-wear wolf.'],
 ["What is a vampire's favorite sport", 'Casketball.'],
 ['Why do mummies have trouble keeping friends',
  "They're too wrapped up in themselves."],
 ['What did one ghost ask another', 'Do humans exist?'],
 ['Who is the most famous ghost detective', 'Shelock Moans.'],
 ['What kind of streets do monsters like the best',
  'Dead ends and skull-de-sacs.'],
 ['What did the skeleton say while riding his Harley Davidson motorcycle',
  'I was bone to be wild.'],
 ['What do ghosts eat for dinner', 'Spook-etti.'],
 ["What is a skeleton's favorite musical instrument", 'A trombone.'],
 ['What do you get when you cross Bambi with a ghost', 'Bam-boo.'],
 ['What did the Mommy ghost say to the baby ghost',
  "Don't spook unless you're spooken to."],
 ['Why do witches fly on broomsticks',
  "Because vacuum cleaners don't have long enough cords."],
 ['How do witches keep their hair in place while flying', 'With scare spray.'],
 ["Why didn't the skeleton cross the road",
  "Because he didn't have the guts!"],
 ['When does a ghost need a license', 'During haunting season.'],
 ['What do Italians eat on Halloween', 'Fetuccini-afraid-o.'],
 ['What monster flies his kite in a rainstorm', 'Benjamin Frankenstein.'],
 ['Where do mummies go for a swim', 'The Dead Sea.'],
 ["What's a vampire's favorite fast food",
  'A guy with very high blood pressure.'],
 ['What happens when a ghost gets lost in the fog', 'He is mist.'],
 ['Who did the vampire take to the prom', 'His ghoul-friend.'],
 ['What happened when the male ghost met the female ghost',
  'It was love at first fright.'],
 ['What do you do when 20 monsters surround your house',
  "Hope it's Halloween!"],
 ['What type of surgery does a vampire doctor perform',
  'Fly-by-night operations.'],
 ['Why did the skeleton cross the road', 'To get to the body shop!'],
 ['Why are demons and ghouls always together',
  "Because demons are a ghoul's best friend."],
 ['Why did the ghost go to the bar', 'For the boo-ze.'],
 ['What do you get when you cross a vampire and a snowman', 'Frostbite.'],
 ['What did one ghost say to the other ghost', 'Do you believe in people?'],
 ['Who does a female ghost see on a Friday night', 'Her boo-friend.'],
 ["What was a witch's favorite subject in school", 'Spelling.'],
 ['Who won the skeleton beauty contest', 'No body.'],
 ['What do you call a ghost that gets too close to a bonfire',
  'A toasty ghosty.'],
 ["What's a monsters favorite play", 'Romeo and Ghouliet.'],
 ['What do people say to the parents of twin witches',
  'Which witch is which?'],
 ["Who goes to the monsters' PTA", 'Mummies and deadies.'],
 ["What happened to the guy who couldn't keep up payments to his exorcist",
  'He was repossessed.'],
 ['What did the skeleton order at the restaurant', 'Spare-ribs.'],
 ["What does the papa ghost say to his family when he's driving",
  'Fasten your sheet-belts.'],
 ['Where do vampires store their money', 'In a blood bank.'],
 ['What do you say to a skeleton going on vacation', 'Bone voyage!'],
 ["What is a vampire's favorite holiday", 'Fangsgiving.'],
 ["What do you give a skeleton for Valentine's Day",
  'Bone-Bones in a heart-shaped box.'],
 ['Where does a ghost go on Saturday night', 'Anywhere he can boo-gie.'],
 ["What do you call a skeleton who won't work", 'Lazy bones.'],
 ['Which skeleton was a famous detective', 'Sherlock Bones.'],
 ['Why did the ghost go the doctor', 'To get his boo-ster shot.'],
 ['What tree does the vampire love the best', 'A ceme-tree.'],
 ["What's the first thing ghosts do when they get into a car",
  'They boo-kle their seatbelts.'],
 ['Why do vampires need mouthwash', 'They have bat breath.'],
 ['What game do little cannibals like to play at parties',
  'Swallow the leader.'],
 ["What is a ghost's favorite mode of transportation", 'A scare-plane.'],
 ["Why couldn't the vampire's wife get to sleep",
  "Because of her husband's coffin."],
 ['Why was the little ghost stupid', 'Because he climbed over walls.'],
 ['Why do ghosts like tall buildings',
  'Because they have a lot of scare-cases.'],
 ['What do ghosts add to their morning cereal', 'Boo-berries.'],
 ['What does a vampire never order at a restaurant', 'A stake sandwich.'],
 ['What does a ghost eat for lunch', 'A boo-logna sandwich.'],
 ['Why are vampire jokes bad', 'Because they are a pain in the neck.'],
 ['Where did the vampire open his savings account', 'At a blood bank.'],
 ['What do you get when you cross a ghost with an owl',
  "Something that scares people and doesn't give a hoot."],
 ['What do short-sighted ghosts wear', 'Spook-tacles.'],
 ['What do you say to a skeleton before he eats', 'Bone appetit!'],
 ['Why do witches fly on brooms', 'Because vacuum cleaners are too heavy.'],
 ["Why don't witches ride their brooms when they're angry",
  "They're afraid of flying off the handle!"]]

joke = choice(jokes)

printer.inverseOn()
printer.print('{}?\n'.format(joke[0]))
printer.inverseOff()

printer.underlineOn()
printer.print('{}\n'.format(joke[1]))
printer.underlineOff()

printer.feed(4)
